### ISSUE TITLE
Using beamerswitch seems to impose 11pt font size

### ISSUE THREAD

**Issue by nplatis** [alex-ball/beamerswitch#1]
I have a presentation with `\documentclass[10pt]{beamer}`. Simply switching to `beamerswitch` seems to impose `[11pt]` (and I also checked with 12pt).

**Comment by alex-ball** [comment]
All that is happening here is that `beamer` is not seeing your font size selection, and therefore it uses the default. `beamerswitch` does not automatically pass on class options to `beamer`, or indeed `article`, to avoid potential confusion when switching between the two. I am happy to be swayed by popular opinion if people think it should.

As explained under ‘Tips for further customization’, the way to convert a document from `beamer` to `beamerswitch` is to convert your original `\documentclass` command into a `\PassOptionsToClass` one (note the change from square brackets to braces):

``` .latex
\PassOptionsToClass{10pt}{beamer}
\documentclass{beamerswitch}
```

**Comment by nplatis** [comment]
...and a relevant warning was issued which I had not noticed. 

Maybe you should make it clearer in the documentation that extra beamer options are not passed on.

**Comment by alex-ball** [comment]
Agreed. I'll reopen and tag this as a documentation issue.

Thank you for your feedback, and for using the class.
