### ISSUE TITLE
also option not producing correct outputs when there is a space in the filename

### ISSUE THREAD

**Issue by dsavransky** [alex-ball/beamerswitch#10]
I'm running across an odd issue where, in cases when the tex filename has spaces in it, the output produced for also={handout} or alsohandout, etc. is identical to the slides output (that is, I get two identical PDFs of the slides, rather than one slides pdf and one handout (this also applies to all the other also options).  Everything works as expected when the filename has no spaces.  

I'm attaching two sets of sample logfiles of compilation of identical tex documents, one called 'test.tex' and one called 'test copy.tex'.  I'm using TeXLive 2018 on macos 10.14.3.  Compilation is via pdflatexmk distributed with TeXShop via the MacTex distribution, modified to turn on shell-escape. 

Thanks for a fantastic tex package. 

[test copy-handout.log](https://github.com/alex-ball/beamerswitch/files/3261883/test.copy-handout.log)
[test copy.log](https://github.com/alex-ball/beamerswitch/files/3261884/test.copy.log)
[test-handout.log](https://github.com/alex-ball/beamerswitch/files/3261885/test-handout.log)
[test.log](https://github.com/alex-ball/beamerswitch/files/3261886/test.log)

**Comment by alex-ball** [comment]
I see what's happening. Look at this line from the logs:

```
runsystem(latexmk -silent -synctex=1 -interaction=batchmode -pdf -jobname="test
 copy"-handout "test copy")...executed.
```

As you can see, when the filename contains spaces, the jobname is automatically wrapped in quote marks. This is harmless on the command line, but messes up beamerswitch's tests, since `{"test copy-handout"}` does not end in `{-handout}`: it ends in `{-handout"}`.

Should be simple enough to fix. Leave it with me.

**Comment by dsavransky** [comment]
Thanks for the amazingly fast turnaround on this.  Fix works great!
