### ISSUE TITLE
Error '\str_case_x:nnTF' deprecated on 2020-01-01

### ISSUE THREAD

**Issue by Briffou** [alex-ball/beamerswitch#13]
With an up to date TexLive distribution, I now have the following error with beamerswitch (v1.6)

`./test.tex:4: Undefined control sequence.
<argument> \LaTeX3 error: 
                '\str_case_x:nnTF' deprecated on 2020-01-01. Use '\str_case_e:n
l.4 \title{TITLE}`

with this minimal example:
```
\documentclass{beamerswitch}
\usetheme{metropolis}
\title{TITLE}
\begin{document}
\maketitle
\begin{frame}
	TEST
\end{frame}
\end{document}
```
I use Lualatex 1.10.0 and beamer 3.57. Do you need any other information ?

**EDIT**: I just saw f2856e6e5c835e03562b436f2df80aafc2e9cf91, which ~~probably~~ solve this issue. Can you make a new release an CTAN please ? Thanks !

**Comment by alex-ball** [comment]
Yes, fix released as v1.6.1. You can grab it from the [releases](https://github.com/alex-ball/beamerswitch/releases) page if you need it urgently.
