### ISSUE TITLE
nup=1 for handouts

### ISSUE THREAD

**Issue by mrwalter** [alex-ball/beamerswitch#14]
I am using beamerswitch and would like to typeset one-slide-per-page handouts. As beamerswitch doesn't support setting 'nup=1' via '\handoutlayout', I am simply trying to pass the 'handout' option to beamer via

  ` \PassOptionsToClass{pdf,handout}{beamer}`

However, this throws the following error:

> (/usr/local/texlive/2019/texmf-dist/tex/latex/beamer/beamerouterthemedefault.st
y)))
! Undefined control sequence.
<argument> \pgfpagesdeclarelayout
                                  {1 by 2} { \edef \pgfpageoptionheight {\th...
l.1130 }

(Note: I am using beamerswitch since I would also like to typeset 1pp and 6pp handouts while also typesetting the main slides)

**Comment by alex-ball** [comment]
When you're in handout mode, Beamerswitch expects the things that it loads itself in handout mode are in fact loaded. You can get rid of that error like so:

```tex
\RequirePackage{pgfpages}
\documentclass[...]{beamerswitch}
```

But you'll still be in nup=6 mode. The only way to get what you want would be to define a one-up mode yourself and trigger it manually:

```tex
\documentclass[handout]{beamerswitch}
\handoutlayout{border=1pt}
\makeatletter
\mode<handout>{%
  % These lines define the new layout
  \pgfpagesdeclarelayout{1 by 1}
  {
    \edef\pgfpageoptionheight{\the\paperheight}
    \edef\pgfpageoptionwidth{\the\paperwidth}
    \edef\pgfpageoptionborder{0pt}
    \def\pgfpageoptionfirstshipout{1}
  }
  {
    \pgfpagesphysicalpageoptions
    {%
      logical pages=1,%
      physical height=\pgfpageoptionheight,%
      physical width=\pgfpageoptionwidth,%
      current logical shipout=\pgfpageoptionfirstshipout%
    }
    \pgfpageslogicalpageoptions{1}
    {%
      border shrink=\pgfpageoptionborder,%
      border code=\beamerswitch@Border,%
      scale=2,%
      resized width=\pgfphysicalwidth,%
      resized height=\pgfphysicalheight,%
      center=\pgfpoint{.5\pgfphysicalwidth}{.5\pgfphysicalheight}%
    }%
  }%
  % These lines activate the above layout
  \def\beamerswitch@nup{1}%
  \pgfpagesuselayout{1 by 1}[\beamerswitch@handoutpaper,%
    landscape,border shrink=\the\beamerswitch@margin]%
}
\makeatother
```

The tricky thing with this is that `resized width` and `resized height` only scale down, not up, so `scale` needs to blow up the page before it is scaled down again. Depending on your slide size and paper size you might need to use a different value, but a value of 2 works for standard beamer slides and A4 paper.
