### ISSUE TITLE
Institutes and maketitle in articlelayout

### ISSUE THREAD

**Issue by pzehner** [alex-ball/beamerswitch#17]
Thank you for developing this very convenient class!

If I have several authors and several institutes, when I use the `maketitle` option of `articlelayout` they seem misaligned. See the example below:

```latex
\documentclass[article]{beamerswitch}

\articlelayout{
  maketitle,
}

\title{My title}
\subtitle{My subtitle}
\author{Georges Abitbol\inst{1} \and Jean Lafritte\inst{2}}
\institute{\inst{1} La Classe \and \inst{2} Institut Cananac}

\begin{document}
  \begin{frame}[plain]
    \maketitle
  \end{frame}
\end{document}
```

![Example picture](https://i.imgur.com/s4JL811.png)

While exactly aligning authors and institutes can be challenging, why not display them with superscripts as in `beamer` mode?

**Comment by alex-ball** [comment]
Why not indeed? There is nothing I have done deliberately in beamerswitch to remove them, and they used to be displayed. My guess is that there has been a breaking change in beamer's article mode, but I will have to do some digging to find out what is going wrong.

**Comment by pzehner** [comment]
You mean it used to be displayed with superscripts in `article` mode?

**Comment by alex-ball** [comment]
I believe so, and the `textinst` option (using text mode instead of math mode for the superscripts) was supposed to be effective in article mode as well.

**Comment by pzehner** [comment]
OK, this `textinst` option makes sense now.
