### ISSUE TITLE
\maketitle does not work outside frame (incompatibility with beamer)

### ISSUE THREAD

**Issue by nplatis** [alex-ball/beamerswitch#2]
The documentation of `beamer` mentions that `\maketitle` works even outside a frame, adding a frame if necessary. This does not seem to happen with `beamerswitch`: using `\maketitle` outside a frame produces nothing at all.

This should probably be amended for compatibility with `beamer`.

**Comment by alex-ball** [comment]
beamerswitch activates beamer in `ignorenonframetext` mode, which is typically what you want if you are switching between beamer and article modes. (This is mentioned in the beamerswitch documentation under 'Choosing the mode of the current run'. See also the beamer documentation under section 21.2, 'Creating handouts using the article mode'.)

You can immediately reverse this decision by adding `\mode<all>` directly after `\begin{document}`:

``` .latex
\documentclass{beamerswitch}
\title{Test title}
\author{Test author}
\date{Test date}

\begin{document}
\mode<all>
\maketitle
\end{document}
```

I will make this clearer in the documentation.
