### ISSUE TITLE
Title page elements are lost if specified after \begin{document}

### ISSUE THREAD

**Issue by nplatis** [alex-ball/beamerswitch#3]
If I specify `\author`, `\title`, `\subtitle`, `\date` etc after `\begin{document}` their values are completely lost. I don't know if this is the "correct" behavior, but using `beamer` they work either before or after `\begin{document}`.

**Comment by alex-ball** [comment]
You really ought to be specifying `\title`, `\author`, `\date`, etc. in the preamble. Some classes and packages may malfunction if you specify them in the document body.

The reason it fails here is that beamerswitch activates beamer in `ignorenonframetext` mode, which is typically what you want if you are switching between beamer and article modes. (This is mentioned in the beamerswitch documentation under 'Choosing the mode of the current run'. See also the beamer documentation under section 21.2, 'Creating handouts using the article mode'.)

You can immediately reverse this decision by adding `\mode<all>` directly after `\begin{document}`:

``` .latex
\documentclass{beamerswitch}

\begin{document}
\mode<all>
\title{Test title}
\author{Test author}
\date{Test date}
\maketitle
\end{document}
```

I will make this clearer in the documentation.
