### ISSUE TITLE
Make step 1 of the quick start guide more user friendly

### ISSUE THREAD

**Issue by fmatter** [alex-ball/beamerswitch#4]
I'm not saying it's *not* user friendly! The documentation and the package itself are absolutely great. It just took me about five minutes to figure out what I'd done wrong when I changed

`\documentclass[10pt]{beamer}`

to 

`\PassOptionsToClass[10pt]{beamer}`

instead of

`\PassOptionsToClass{10pt}{beamer}`

For stupid users like me, it might be worth pointing out that detail in step 1 of the quick start guide.

**Comment by alex-ball** [comment]
Thank you for taking the time to suggest that improvement.

I have added a note to the documentation so others will not be caught out similarly. I can't guarantee when the next release will be, but it will be included.
