### ISSUE TITLE
Handout layout 

### ISSUE THREAD

**Issue by Briffou** [alex-ball/beamerswitch#8]
Consider the following two minimal examples, the first one with "standard" handout from beamer class and the manual use  of pgfpages :
```
\documentclass[handout]{beamer}

\usepackage{pgfpages}
\pgfpagesuselayout{2 on 1}[letterpaper]

\usetheme[numbering=fraction]{metropolis}

\begin{document}
\begin{frame}{First}
  This is a text in first frame.
\end{frame}

\begin{frame}{Second}
  This is a text in second frame.
\end{frame}
\end{document}
```
and the second one using beamerswitch : 
```
\documentclass[handout]{beamerswitch}

\handoutlayout{nup=2,paper=letterpaper}

\usetheme[numbering=fraction]{metropolis}

\begin{document}
\begin{frame}{First}
  This is a text in first frame.
\end{frame}

\begin{frame}{Second}
  This is a text in second frame.
\end{frame}
\end{document}
```
Using xelatex (texlive 2018), the resulting .pdf is quite different. With beamerswitch (second example), slides appear "smaller" in the page compared to the first example. Is it possible to have the "same rendering" using beamerswitch than using beamer+pgfpages ?

**Comment by Briffou** [comment]
I managed to get something with beamerswitch by adding
```
\pgfpageslogicalpageoptions{1}
{%
  scale=1.3,%
  center=\pgfpoint{.5\pgfphysicalwidth}{.74\pgfphysicalheight}%
}%
\pgfpageslogicalpageoptions{2}
{%
 scale=1.3,%
 center=\pgfpoint{.5\pgfphysicalwidth}{.26\pgfphysicalheight}%
}%
```
in preamble.

**Comment by alex-ball** [comment]
For the sake of flexibility I would rather not brute-force the scaling.

What causes the issue is that when `\pgfpagesuselayout` is called on a second (or third...) occasion, those subsequent calls do not fully overwrite the changes made by the first. You can see this if you change your first example (using standard beamer) from

```tex
\pgfpagesuselayout{2 on 1}[letterpaper]
```

to 

```tex
\pgfpagesuselayout{16 on 1}[letterpaper]
\pgfpagesuselayout{2 on 1}[letterpaper]
```

At the time of writing, beamerswitch sets defaults like this

```tex
\handoutlayout{paper=a4paper,nup=6}
```

meaning that the slides never go larger than if you had specified nup=6 yourself (but they do go smaller).

I am not sure when this started happening, but I am sure it is a bug in pgfpages. The manual says:  ‘If this function is called multiple times, only the last call “wins.” You can thereby overwrite any previous
settings. In particular, layouts *do not* accumulate.’ which contradicts the behaviour currently being seen.

I will see what I can do from my end, but this really needs to be fixed at the PGF end.

**Comment by Briffou** [comment]
Ok, I see. I agree that the "scale" option is just a workaround for my case, clearly not a solution !

**Comment by alex-ball** [comment]
Bug reported upstream here:
<https://sourceforge.net/p/pgf/bugs/491/>.

Beamerswitch v1.4 will add an option to control the whitespace around the slides in handout mode. Commit d7bac16f4fa4812e5da1bf15253ada8fe9106354 also changes the way the defaults are set to avoid triggering this bug.

**Comment by Briffou** [comment]
I just tried with v1.4, and is it me or your recent modifications only works when you have 2 frames ? Can you try the following :
```
\documentclass[handout]{beamerswitch}

\handoutlayout{nup=2,paper=letterpaper,border=0.4pt}
\usetheme[numbering=fraction]{metropolis}

\begin{document}
\begin{frame}{First}
  This is a text in first frame.
\end{frame}

\begin{frame}{Second}
  This is a text in second frame.
\end{frame}

\begin{frame}{Third}
  This is a text in third frame.
\end{frame}
\end{document}
```
The first page is OK (and the first 2 frames have the "right size") but the third frame on the second page is not at the right position. I observe this as soon as I checkout on commit d7bac16f4fa4812e5

**Comment by alex-ball** [comment]
I see no problem using LuaLaTeX or PDFLaTeX:

![test4](https://user-images.githubusercontent.com/1890395/44976019-dbd73900-af5b-11e8-8910-f561fc7e4f6e.png)

However, I see something goes a bit screwy using XeLaTeX. Bear with me while I investigate...

**Comment by alex-ball** [comment]
Okay, this is a bug that existed before but was much harder to trigger. Since the cause is different, I will leave this issue closed and start a new one: see Issue #9.

**Comment by Briffou** [comment]
I confirm that everything is working now with XeLaTeX. Thanks ! 
Will there be a new release on CTAN including commit c01fb5eab2e9a3906 ?

**Comment by alex-ball** [comment]
Yes, I just want to check everything over again before pushing the code out. Thanks for testing the changes!
